user: "$" # the user to query, all by default
partition: optimal # the partition to query, optimal by default
cycle: 60 # pjkill run every cycle time in minute, 60 by default
jp_timeout: 4 # jupyter jobs timeout limit in hour, 4 by default
jp_ngpu: 2 # gpu limit of every jupyter job, 2 by default
jp_njob: 8 # jupyter job number limit of every user, 2 by default
reserved_ngpu: 8 # reserved gpu limit of every user, 12 by default
spot_ngpu: 32 # spot gpu limit of every user, 32 by default
SUDO_PASSWD: 123456 # the passwd for sudo authorization

# capture by CMD
sweep: False # sweep around every cycle, False by default
unkill: False # unkill the job to stay safe False by default
version: False # display version and exit, False by default